// Code generated by protoc-gen-validatex. DO NOT EDIT.

// versions:
//  protoc-gen-validatex v0.0.1-dev

package main

import (
	context "context"
	fmt "fmt"
	i18n "github.com/nicksnyder/go-i18n/v2/i18n"
	validatex "github.com/protoc-gen/protoc-gen-validatex/pkg/validatex"
)

func (x *SignUpRequest) Validate(ctx context.Context) error {
	if x == nil {
		return nil
	}
	if validatex.ValidEmail(x.Email) != nil {
		return fmt.Errorf(validatex.MustLocalize(ctx,
			&i18n.LocalizeConfig{MessageID: "EmailInvalid", TemplateData: map[string]string{"FieldName": "email"}},
			"field email must be a valid email"))
	}
	if len(x.Password) < 5 {
		return fmt.Errorf("field password must have at least 5 characters")
	}
	if len(x.Password) > 50 {
		return fmt.Errorf("field password must have at most 50 characters")
	}
	return nil
}

func init() {
	validatex.Init18n("./example/i18n")
}
